# Generated by Django 5.1.8 on 2025-05-10 11:41

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_avatar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Sejong Cloud/users/avatars",
            ),
        ),
    ]
