# Generated by Django 5.1.8 on 2025-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
