# Generated by Django 5.1.8 on 2025-11-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_id',
            field=models.CharField(blank=True, default='https://drive.google.com/file/d/1vwR-0IPCf2LpL2e8EsTfR9zxi5gbZCH0/view?usp=sharing', max_length=250, null=True),
        ),
    ]
