# Generated by Django 5.1.8 on 2025-11-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_avatar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_id',
            field=models.CharField(blank=True, default='https://drive.google.com/uc?id=1FCfMdEvghunhDuKd1PWQqty_ZPZelqim', max_length=250, null=True),
        ),
    ]
