# Generated by Django 6.0.5 on 2026-05-31 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_avatar_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groups",
            options={
                "ordering": ["name"],
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="groups",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название группы"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер должен начинаться с '+992' и содержать 9 цифр после него.",
                        regex="^\\+992\\d{9}$",
                    )
                ],
            ),
        ),
    ]
