# Generated by Django 5.1.8 on 2025-05-10 11:41

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary", "0002_alter_book_cover_id_alter_book_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Sejong Cloud/book/covers",
                verbose_name="Cover",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Sejong Cloud/book/files",
            ),
        ),
    ]
