# Generated by Django 5.1.8 on 2025-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary", "0003_alter_book_cover_alter_book_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="file_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
