# Generated by Django 5.1.8 on 2025-12-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0004_alter_book_cover_id_alter_book_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='description_eng',
            field=models.TextField(default='', help_text='Book description in English'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_kor',
            field=models.TextField(default='', help_text='Book description in Korean'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_rus',
            field=models.TextField(default='', help_text='Book description in Russian'),
        ),
        migrations.AddField(
            model_name='book',
            name='description_taj',
            field=models.TextField(default='', help_text='Book description in Tajik'),
        ),
        migrations.AddField(
            model_name='book',
            name='title_eng',
            field=models.CharField(default='', help_text='Book title English', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='title_kor',
            field=models.CharField(default='', help_text='Book title Korean', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='title_rus',
            field=models.CharField(default='', help_text='Book title Russian', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='title_taj',
            field=models.CharField(default='', help_text='Book title Tajik', max_length=200),
        ),
    ]
