# Generated by Django 5.1.8 on 2025-12-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elibrary', '0005_remove_book_description_remove_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description_eng',
            field=models.TextField(verbose_name='Book description in English'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description_kor',
            field=models.TextField(verbose_name='Book description in Korean'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description_rus',
            field=models.TextField(verbose_name='Book description in Russian'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description_taj',
            field=models.TextField(verbose_name='Book description in Tajik'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_eng',
            field=models.CharField(max_length=200, verbose_name='Book title English'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_kor',
            field=models.CharField(max_length=200, verbose_name='Book title Korean'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_rus',
            field=models.CharField(max_length=200, verbose_name='Book title Russian'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title_taj',
            field=models.CharField(max_length=200, verbose_name='Book title Tajik'),
        ),
    ]
