# Generated by Django 6.0.5 on 2026-05-31 12:46

import django.utils.timezone
import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elibrary", "0006_alter_book_description_eng_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=255, verbose_name="Автор"),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Sejong Cloud/book/covers",
                verbose_name="Обложка",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Добавлено"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="description_eng",
            field=models.TextField(verbose_name="Описание (англ.)"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description_kor",
            field=models.TextField(verbose_name="Описание (кор.)"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description_rus",
            field=models.TextField(verbose_name="Описание (рус.)"),
        ),
        migrations.AlterField(
            model_name="book",
            name="description_taj",
            field=models.TextField(verbose_name="Описание (тадж.)"),
        ),
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Sejong Cloud/book/files",
                verbose_name="Файл книги",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genres",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Книги Sejong", "Книги Sejong"),
                    ("Книги Topik", "Книги Topik"),
                    ("Художественная литература", "Художественная литература"),
                ],
                max_length=30,
                verbose_name="Жанр",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата публикации"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title_eng",
            field=models.CharField(max_length=200, verbose_name="Название (англ.)"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title_kor",
            field=models.CharField(max_length=200, verbose_name="Название (кор.)"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title_rus",
            field=models.CharField(max_length=200, verbose_name="Название (рус.)"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title_taj",
            field=models.CharField(max_length=200, verbose_name="Название (тадж.)"),
        ),
    ]
