# Generated by Django 5.1.8 on 2025-05-10 08:26

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="custom_id",
            field=models.IntegerField(
                blank=True,
                help_text="<strong><span style='font-size: 16px;'>Don't touch!!!</span></strong>",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="images",
            field=models.JSONField(
                blank=True,
                help_text="<strong><span style='font-size: 16px;'>Don't touch!!!</span></strong>",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcementimage",
            name="google_drive_file_id",
            field=models.CharField(
                blank=True,
                help_text="<strong><span style='font-size: 16px;'>Don't touch!!!</span></strong>",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="announcementimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image file",
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="SejongApp/announcement/images",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="time",
            field=models.JSONField(
                blank=True,
                help_text="<strong><span style='font-size: 16px;'>Don't touch!!!</span></strong>",
                null=True,
            ),
        ),
    ]
