# Generated by Django 5.1.8 on 2025-05-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0002_alter_announcement_custom_id_and_more"),
        ("users", "0002_alter_user_avatar_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="group",
        ),
        migrations.AddField(
            model_name="schedule",
            name="group",
            field=models.ManyToManyField(help_text="Group name", to="users.groups"),
        ),
    ]
