# Generated by Django 5.1.8 on 2025-05-10 11:41

import gdstorage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0003_remove_schedule_group_schedule_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image file",
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Sejong Cloud/announcement/images",
            ),
        ),
    ]
