# Generated by Django 5.1.8 on 2025-06-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0004_alter_announcementimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="custom_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="images",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="announcementimage",
            name="google_drive_file_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="time",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
