# Generated by Django 5.1.8 on 2025-08-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_announcement_custom_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='content',
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_eng',
            field=models.TextField(default='', help_text='Announcement content in English'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_kor',
            field=models.TextField(default='', help_text='Announcement content in Korean'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_rus',
            field=models.TextField(default='', help_text='Announcement content in Russian'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='content_taj',
            field=models.TextField(default='', help_text='Announcement content in Tajik'),
        ),
    ]
