# Generated by Django 5.1.8 on 2025-08-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_remove_announcement_content_announcement_content_eng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='title',
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_eng',
            field=models.CharField(default='', help_text='Announcement title English', max_length=200),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_kor',
            field=models.CharField(default='', help_text='Announcement title Korean', max_length=200),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_rus',
            field=models.CharField(default='', help_text='Announcement title Russian', max_length=200),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_taj',
            field=models.CharField(default='', help_text='Announcement title Tajik', max_length=200),
        ),
    ]
