# Generated by Django 5.1.8 on 2025-11-24 09:29

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_announcement_title_announcement_title_eng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_taj', models.CharField(default='', help_text='Notice title Tajik', max_length=200)),
                ('title_rus', models.CharField(default='', help_text='Notice title Russian', max_length=200)),
                ('title_eng', models.CharField(default='', help_text='Notice title English', max_length=200)),
                ('title_kor', models.CharField(default='', help_text='Notice title Korean', max_length=200)),
                ('content_taj', models.TextField(default='', help_text='Notice content in Tajik')),
                ('content_rus', models.TextField(default='', help_text='Notice content in Russian')),
                ('content_eng', models.TextField(default='', help_text='Notice content in English')),
                ('content_kor', models.TextField(default='', help_text='Notice content in Korean')),
                ('images', models.ImageField(help_text='Image file', upload_to='')),
            ],
            options={
                'db_table': 'notices',
            },
        ),
    ]
