# Generated by Django 5.1.8 on 2025-11-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='images',
        ),
    ]
