# Generated by Django 5.1.8 on 2026-03-13 12:09

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_notice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiChat',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text="Вопрос студента (например: 'Переведи слово 안녕하세요')")),
                ('answer', models.TextField(help_text='Ответ Gemini на вопрос студента')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время отправки вопроса')),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь, который задал вопрос', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gemini_chats',
                'ordering': ['-created_at'],
            },
        ),
    ]
