# Generated by Django 5.1.8 on 2026-03-27 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_geminichat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geminichat',
            options={'ordering': ['-time']},
        ),
        migrations.RenameField(
            model_name='geminichat',
            old_name='created_at',
            new_name='time',
        ),
    ]
