# Generated by Django 5.1.8 on 2025-12-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_remove_notice_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='version_number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
