# Generated by Django 5.1.8 on 2026-04-01 11:58

import django.db.models.deletion
import django_mongodb_backend.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_alter_geminichat_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geminichat',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='geminichat',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='geminichat',
            name='question',
        ),
        migrations.RemoveField(
            model_name='geminichat',
            name='time',
        ),
        migrations.AddField(
            model_name='geminichat',
            name='chat_id',
            field=models.CharField(default='unknown', help_text='ID чата, приходит с фронтенда', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='geminichat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата создания чата', null=True),
        ),
        migrations.AddField(
            model_name='geminichat',
            name='title',
            field=models.CharField(blank=True, help_text='Название чата', max_length=255),
        ),
        migrations.AlterField(
            model_name='geminichat',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Пользователь, который задал вопрос', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GeminiMessage',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Вопрос пользователя')),
                ('answer', models.TextField(help_text='Ответ Gemini')),
                ('time', models.DateTimeField(auto_now_add=True, help_text='Время сообщения')),
                ('chat', models.ForeignKey(help_text='К какому чату относится', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='info.geminichat')),
            ],
            options={
                'db_table': 'gemini_messages',
                'ordering': ['time'],
            },
        ),
    ]
