# Generated by Django 5.1.8 on 2026-04-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_geminichat_options_remove_geminichat_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geminichat',
            name='chat_id',
            field=models.CharField(help_text='ID чата, приходит с фронтенда', max_length=255, unique=True),
        ),
    ]
