# Generated by Django 6.0.5 on 2026-05-31 12:46

import django.db.models.deletion
import gdstorage.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0012_alter_geminichat_chat_id"),
        ("users", "0008_alter_groups_options_alter_user_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ["-time_posted"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.AlterModelOptions(
            name="announcementimage",
            options={
                "verbose_name": "Изображение объявления",
                "verbose_name_plural": "Изображения объявлений",
            },
        ),
        migrations.AlterModelOptions(
            name="geminichat",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Чат Gemini",
                "verbose_name_plural": "Чаты Gemini",
            },
        ),
        migrations.AlterModelOptions(
            name="geminimessage",
            options={
                "ordering": ["time"],
                "verbose_name": "Сообщение Gemini",
                "verbose_name_plural": "Сообщения Gemini",
            },
        ),
        migrations.AlterModelOptions(
            name="notice",
            options={
                "ordering": ["-version_number"],
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Расписание", "verbose_name_plural": "Расписания"},
        ),
        migrations.AlterModelOptions(
            name="timeslot",
            options={
                "ordering": ["day", "start_time"],
                "verbose_name": "Временной слот",
                "verbose_name_plural": "Временные слоты",
            },
        ),
        migrations.AlterField(
            model_name="announcement",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content_eng",
            field=models.TextField(default="", help_text="Текст (англ.)"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content_kor",
            field=models.TextField(default="", help_text="Текст (кор.)"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content_rus",
            field=models.TextField(default="", help_text="Текст (рус.)"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="content_taj",
            field=models.TextField(default="", help_text="Текст (тадж.)"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="images_many_to_many",
            field=models.ManyToManyField(blank=True, to="info.announcementimage"),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="time_posted",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title_eng",
            field=models.CharField(
                default="", help_text="Заголовок (англ.)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title_kor",
            field=models.CharField(
                default="", help_text="Заголовок (кор.)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title_rus",
            field=models.CharField(
                default="", help_text="Заголовок (рус.)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title_taj",
            field=models.CharField(
                default="", help_text="Заголовок (тадж.)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="announcementimage",
            name="google_drive_file_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="announcementimage",
            name="image",
            field=models.ImageField(
                blank=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Sejong Cloud/announcement/images",
            ),
        ),
        migrations.AlterField(
            model_name="announcementimage",
            name="title",
            field=models.CharField(help_text="Заголовок изображения", max_length=200),
        ),
        migrations.AlterField(
            model_name="geminichat",
            name="chat_id",
            field=models.CharField(
                help_text="ID чата с фронтенда", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="geminichat",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="geminichat",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="geminichat",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="geminimessage",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="info.geminichat",
            ),
        ),
        migrations.AlterField(
            model_name="geminimessage",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content_eng",
            field=models.TextField(default="", help_text="Текст (англ.)"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content_kor",
            field=models.TextField(default="", help_text="Текст (кор.)"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content_rus",
            field=models.TextField(default="", help_text="Текст (рус.)"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="content_taj",
            field=models.TextField(default="", help_text="Текст (тадж.)"),
        ),
        migrations.AlterField(
            model_name="notice",
            name="images",
            field=models.ImageField(
                help_text="Изображение",
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="Sejong Cloud/notice/images",
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title_eng",
            field=models.CharField(
                default="", help_text="Заголовок (англ.)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title_kor",
            field=models.CharField(
                default="", help_text="Заголовок (кор.)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title_rus",
            field=models.CharField(
                default="", help_text="Заголовок (рус.)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="title_taj",
            field=models.CharField(
                default="", help_text="Заголовок (тадж.)", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="version_number",
            field=models.FloatField(help_text="Номер версии"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="book",
            field=models.IntegerField(
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                ],
                help_text="Номер книги (1–8)",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="group",
            field=models.ManyToManyField(help_text="Группа", to="users.groups"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="teacher",
            field=models.CharField(help_text="Преподаватель", max_length=100),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="time_many_to_many",
            field=models.ManyToManyField(
                help_text="Временные слоты", to="info.timeslot"
            ),
        ),
    ]
